name: sklearnprod0
dependencies:
  - python=3
  - cython
  - graphviz
  - pip
  - pip:
      - nose-timer
      - wheelhouse_uploader
      - nose
      - Wheel
      - numpy
      - scipy
      - graphviz
      - jupyter
      - pandas
      - matplotlib
      - pillow
      - graphviz
