name: sklearnprod0
dependencies:
  - python=3
  - scikit-learn
  - numpy
  - scipy
  - cython
  - jupyter
  - pandas
  - pip
  - pip:
      - nose-timer
      - wheelhouse_uploader
      - nose
      - Wheel